In [1]:
from UTILITY_quickstart import *

In [2]:
importedDefaultSettings = loadConfig("setLattice_configs/defaults.yml")

tao = initializeTao(
#    inputBeamFilePathSuffix = inputBeamFilePathSuffix,
    
#    csrTF = csrTF,
#    numMacroParticles=1e5,
    scratchPath = "/tmp",
    randomizeFileNames = True
)

Environment set to:  /Users/nmajik/Documents/SLAC/FACET2-Bmad-PyTao
Tracking to end
CSR off
Overwriting lattice with setLattice() defaults
No defaults file provided to setLattice(). Using setLattice_configs/defaults.yml
WARNING! No beam file is specified!
Number of macro particles defined by input file
Beam created, written to /tmp/beams/activeBeamFile_18091071165107380308.h5, and reinit to tao

In [3]:
setLattice(tao, **importedDefaultSettings)

launchTwissCorrection(tao)

No evalElement provided. Assuming golden lattice PR10571
Optimization Results:
Optimal Parameters: [0.13755483 0.95354498 0.40561992 2.20428422]
Objective Function Value at Optimal Parameters: 1.5713418828625716e-09
Number of Iterations: 93
Converged: True

In [4]:
baselineTransport = getMatrix(tao, "BEGBC20", "MFFF", print = True)

In [5]:
quadsToTweak = "Q1EkG"

for quadsToTweak in ["Q1EkG", "Q2EkG", "Q3EkG", "Q4EkG", "Q5EkG", "Q6EkG"]:
    print(quadsToTweak)
    setLattice(tao, **(importedDefaultSettings | { quadsToTweak : importedDefaultSettings[quadsToTweak] + 1 }))
    
    newMatrix = getMatrix(tao, "BEGBC20", "MFFF")
    deltaMatrix = newMatrix - baselineTransport
    displayMatrix(deltaMatrix)

Q1EkG

Q2EkG

Q3EkG

Q4EkG

Q5EkG

Q6EkG

In [6]:
quadsToTweak = "Q1EkG"

for quadsToTweak in ["Q1EkG", "Q2EkG", "Q3EkG", "Q4EkG", "Q5EkG", "Q6EkG"]:
    print(quadsToTweak)
    setLattice(tao, **(importedDefaultSettings | { quadsToTweak : importedDefaultSettings[quadsToTweak] * 1.01 }))
    
    newMatrix = getMatrix(tao, "BEGBC20", "MFFF")
    deltaMatrix = newMatrix - baselineTransport
    displayMatrix(deltaMatrix)

Q1EkG

Q2EkG

Q3EkG

Q4EkG

Q5EkG

Q6EkG

## BC14

In [7]:
baselineTransport = getMatrix(tao, "BEGBC14_1", "ENDBC14_2", print = True)

In [8]:
tao.cmd("show lat QUAD::*")

['# Values shown are for the Exit End of each Element:',
 '# Index  name      key                       s       l    beta   phi_a    eta   orbit    beta   phi_b    eta   orbit  Track',
 '#                                                            a   [2pi]      x  x [mm]       b   [2pi]      y  y [mm]  State',
 '     41  QA10361   Quadrupole            4.466   0.108   58.88   0.376   0.00   0.000   50.47   0.437   0.00   0.000  Alive',
 '     45  QA10371#1 Quadrupole            4.741   0.054  101.72   0.377   0.00   0.000   23.94   0.438   0.00   0.000  Alive',
 '     47  QA10371#2 Quadrupole            4.795   0.054  101.89   0.377   0.00   0.000   21.98   0.438   0.00   0.000  Alive',
 '     68  QE10425#1 Quadrupole            8.052   0.054    0.11   0.665   0.00   0.000    9.08   0.903   0.00   0.000  Alive',
 '     70  QE10425#2 Quadrupole            8.106   0.054    0.19   0.725   0.00   0.000    8.31   0.904   0.00   0.000  Alive',
 '     76  QE10441   Quadrupole            8.507   0.108    2.38   0.814   0.00   0.000    2.25   0.921   0.00   0.000  Alive',
 '    101  QE10511#1 Quadrupole           11.145   0.054    3.36   0.999  -0.00   0.000    2.21   1.128  -0.00  -0.000  Alive',
 '    103  QE10511#2 Quadrupole           11.199   0.054    3.10   1.002  -0.00   0.000    2.49   1.132  -0.00  -0.000  Alive',
 '    108  QE10525#1 Quadrupole           11.535   0.054    1.31   1.029  -0.00   0.000    5.29   1.146  -0.00  -0.000  Alive',
 '    110  QE10525#2 Quadrupole           11.589   0.054    1.22   1.035  -0.00   0.000    5.35   1.148  -0.00  -0.000  Alive',
 '    132  QM10631#1 Quadrupole           15.917   0.054   15.19   1.310   0.00  -0.000    3.76   1.367  -0.00   0.000  Alive',
 '    134  QM10631#2 Quadrupole           15.971   0.054   14.10   1.311   0.00  -0.000    4.21   1.369  -0.00   0.000  Alive',
 '    139  QM10651#1 Quadrupole           16.473   0.054    3.57   1.322   0.00  -0.000   11.40   1.380  -0.00   0.000  Alive',
 '    141  QM10651#2 Quadrupole           16.527   0.054    3.19   1.325   0.00  -0.000   11.27   1.381  -0.00   0.000  Alive',
 '    151  QB10731#1 Quadrupole           17.734   0.053    0.44   1.549  -0.26  -0.000    0.57   1.455   0.00   0.000  Alive',
 '    153  QB10731#2 Quadrupole           17.787   0.053    0.39   1.570  -0.25  -0.000    0.51   1.471   0.00   0.000  Alive',
 '    162  QM10771#1 Quadrupole           19.134   0.054    5.38   1.873   0.00   0.000    2.75   1.691   0.00   0.000  Alive',
 '    164  QM10771#2 Quadrupole           19.188   0.054    6.41   1.874   0.00   0.000    2.64   1.694   0.00   0.000  Alive',
 '    166  QM10781#1 Quadrupole           19.539   0.054   16.76   1.880   0.00   0.000    1.63   1.722   0.00   0.000  Alive',
 '    168  QM10781#2 Quadrupole           19.593   0.054   17.04   1.880   0.00   0.000    1.67   1.727   0.00   0.000  Alive',
 '    181  QA11132#1 Quadrupole           22.851   0.053    3.53   1.949  -0.00   0.000   19.78   1.822   0.00  -0.000  Alive',
 '    183  QA11132#2 Quadrupole           22.904   0.053    3.51   1.952  -0.00   0.000   19.76   1.822   0.00  -0.000  Alive',
 '    191  Q11201#1  Quadrupole           29.111   0.053   14.99   2.113   0.00   0.000    5.45   1.924  -0.00  -0.000  Alive',
 '    193  Q11201#2  Quadrupole           29.164   0.053   14.95   2.114   0.00   0.000    5.48   1.926  -0.00  -0.000  Alive',
 '    202  QA11265#1 Quadrupole           35.192   0.053    7.21   2.212   0.00   0.000   20.70   2.021  -0.00  -0.000  Alive',
 '    204  QA11265#2 Quadrupole           35.245   0.053    7.19   2.213   0.00   0.000   20.91   2.021  -0.00  -0.000  Alive',
 '    211  Q11301#1  Quadrupole           38.433   0.053    7.36   2.286   0.00   0.000   35.38   2.040  -0.00  -0.000  Alive',
 '    213  Q11301#2  Quadrupole           38.486   0.053    7.59   2.287   0.00   0.000   34.71   2.040  -0.00  -0.000  Alive',
 '    227  QM11312#1 Quadrupole           40.015   0.053   18.63   2.307   0.00   0.000   12.49   2.052  -0.00  -0.000  Alive',
 '    229  QM11312#2 Quadrupole           40.068   0.053   18.57   2.308   0.00   0.000   12.27   2.053  -0.00  -0.000  Alive',
 '    236  CQ11317   Quadrupole           41.583   0.108   12.40   2.323  -0.10  -0.000    9.20   2.075  -0.00  -0.000  Alive',
 '    254  SQ11340   Quadrupole           45.731   0.108    3.55   2.431  -0.11  -0.000    3.31   2.199  -0.00  -0.000  Alive',
 '    256  CQ11352   Quadrupole           46.008   0.108    3.36   2.443  -0.08  -0.000    3.18   2.212  -0.00  -0.000  Alive',
 '    266  QM11358#1 Quadrupole           47.341   0.053    3.20   2.511   0.00  -0.000    3.03   2.281   0.00  -0.000  Alive',
 '    268  QM11358#2 Quadrupole           47.394   0.053    3.39   2.513   0.00  -0.000    2.89   2.284   0.00  -0.000  Alive',
 '    273  QM11362#1 Quadrupole           47.996   0.053    6.72   2.533   0.00  -0.000    1.28   2.336   0.00  -0.000  Alive',
 '    275  QM11362#2 Quadrupole           48.050   0.053    6.55   2.534   0.00  -0.000    1.28   2.342   0.00  -0.000  Alive',
 '    283  QM11393#1 Quadrupole           52.917   0.053   16.24   2.956  -0.00   0.000   25.96   2.500   0.00   0.000  Alive',
 '    285  QM11393#2 Quadrupole           52.970   0.053   17.66   2.956  -0.00   0.000   25.13   2.500   0.00   0.000  Alive',
 '    290  Q11401#1  Quadrupole           53.831   0.053   56.25   2.960  -0.00   0.000    9.10   2.509   0.00   0.000  Alive',
 '    292  Q11401#2  Quadrupole           53.885   0.053   56.79   2.961  -0.00   0.000    8.77   2.510   0.00   0.000  Alive',
 '    313  Q11501#1  Quadrupole           66.176   0.053    7.72   3.060  -0.00   0.000   35.32   2.888  -0.00   0.000  Alive',
 '    315  Q11501#2  Quadrupole           66.229   0.053    7.73   3.061  -0.00   0.000   35.31   2.889  -0.00   0.000  Alive',
 '    325  Q11601#1  Quadrupole           78.520   0.053   40.28   3.183  -0.00   0.000   12.27   2.989  -0.00  -0.000  Alive',
 '    327  Q11601#2  Quadrupole           78.573   0.053   40.23   3.183  -0.00   0.000   12.32   2.990  -0.00  -0.000  Alive',
 '    346  Q11701#1  Quadrupole           90.864   0.053   17.41   3.260   0.00  -0.000   47.87   3.074  -0.00  -0.000  Alive',
 '    348  Q11701#2  Quadrupole           90.918   0.053   17.45   3.260   0.00  -0.000   47.85   3.074  -0.00  -0.000  Alive',
 '    360  Q11801#1  Quadrupole          103.209   0.053   46.01   3.332   0.00  -0.000   28.81   3.128  -0.00  -0.000  Alive',
 '    362  Q11801#2  Quadrupole          103.262   0.053   45.97   3.332   0.00  -0.000   28.89   3.128  -0.00  -0.000  Alive',
 '    371  Q11901#1  Quadrupole          115.872   0.053   26.87   3.390   0.00  -0.000   70.97   3.173  -0.00  -0.000  Alive',
 '    373  Q11901#2  Quadrupole          115.926   0.053   26.95   3.391   0.00  -0.000   70.86   3.173  -0.00  -0.000  Alive',
 '    386  Q12201#1  Quadrupole          130.742   0.053   79.80   3.442   0.00  -0.000   24.62   3.231  -0.00  -0.000  Alive',
 '    388  Q12201#2  Quadrupole          130.796   0.053   79.68   3.442   0.00  -0.000   24.63   3.231  -0.00  -0.000  Alive',
 '    402  Q12301#1  Quadrupole          143.087   0.053   35.30   3.480   0.00  -0.000   43.39   3.292   0.00  -0.000  Alive',
 '    404  Q12301#2  Quadrupole          143.140   0.053   35.31   3.480   0.00  -0.000   43.32   3.292   0.00  -0.000  Alive',
 '    415  Q12401#1  Quadrupole          155.431   0.053   54.62   3.525   0.00  -0.000   21.22   3.359   0.00  -0.000  Alive',
 '    417  Q12401#2  Quadrupole          155.485   0.053   54.51   3.525   0.00  -0.000   21.25   3.359   0.00  -0.000  Alive',
 '    428  Q12501#1  Quadrupole          167.776   0.053   22.36   3.582   0.00  -0.000   43.99   3.425   0.00  -0.000  Alive',
 '    430  Q12501#2  Quadrupole          167.829   0.053   22.37   3.583   0.00  -0.000   43.93   3.425   0.00  -0.000  Alive',
 '    441  Q12601#1  Quadrupole          180.120   0.053   41.32   3.649   0.00  -0.000   22.32   3.489   0.00   0.000  Alive',
 '    443  Q12601#2  Quadrupole          180.173   0.053   41.24   3.649   0.00  -0.000   22.38   3.490   0.00   0.000  Alive',
 '    454  Q12701#1  Quadrupole          192.464   0.053   17.62   3.724   0.00   0.000   53.88   3.547   0.00   0.000  Alive',
 '    456  Q12701#2  Quadrupole          192.518   0.053   17.66   3.725   0.00   0.000   53.80   3.548   0.00   0.000  Alive',
 '    467  Q12801#1  Quadrupole          204.809   0.053   43.60   3.798  -0.00   0.000   23.82   3.603   0.00   0.000  Alive',
 '    469  Q12801#2  Quadrupole          204.862   0.053   43.54   3.798  -0.00   0.000   23.86   3.604   0.00   0.000  Alive',
 '    484  Q12901#1  Quadrupole          217.472   0.053   20.23   3.868  -0.00   0.000   53.36   3.661   0.00   0.000  Alive',
 '    486  Q12901#2  Quadrupole          217.526   0.053   20.28   3.868  -0.00   0.000   53.27   3.661   0.00   0.000  Alive',
 '    495  Q13201#1  Quadrupole          232.342   0.053   58.54   3.939  -0.00   0.000   18.46   3.740   0.00   0.000  Alive',
 '    497  Q13201#2  Quadrupole          232.396   0.053   58.44   3.939  -0.00   0.000   18.49   3.740   0.00   0.000  Alive',
 '    508  Q13301#1  Quadrupole          244.687   0.053   24.81   3.992  -0.00   0.000   42.29   3.812  -0.00   0.000  Alive',
 '    510  Q13301#2  Quadrupole          244.740   0.053   24.85   3.992  -0.00   0.000   42.22   3.813  -0.00   0.000  Alive',
 '    521  Q13401#1  Quadrupole          257.031   0.053   51.73   4.048  -0.00   0.000   18.62   3.885  -0.00   0.000  Alive',
 '    523  Q13401#2  Quadrupole          257.085   0.053   51.63   4.048  -0.00   0.000   18.66   3.885  -0.00   0.000  Alive',
 '    534  Q13501#1  Quadrupole          269.376   0.053   19.70   4.111  -0.00   0.000   45.96   3.954  -0.00   0.000  Alive',
 '    536  Q13501#2  Quadrupole          269.429   0.053   19.72   4.111  -0.00   0.000   45.90   3.954  -0.00   0.000  Alive',
 '    547  Q13601#1  Quadrupole          281.720   0.053   39.81   4.183  -0.00   0.000   22.75   4.017  -0.00  -0.000  Alive',
 '    549  Q13601#2  Quadrupole          281.773   0.053   39.74   4.184  -0.00   0.000   22.80   4.017  -0.00  -0.000  Alive',
 '    560  Q13701#1  Quadrupole          294.064   0.053   17.72   4.260   0.00  -0.000   55.29   4.073  -0.00  -0.000  Alive',
 '    562  Q13701#2  Quadrupole          294.118   0.053   17.77   4.261   0.00  -0.000   55.20   4.073  -0.00  -0.000  Alive',
 '    573  Q13801#1  Quadrupole          306.409   0.053   47.00   4.331   0.00  -0.000   22.50   4.130  -0.00  -0.000  Alive',
 '    575  Q13801#2  Quadrupole          306.462   0.053   46.92   4.331   0.00  -0.000   22.53   4.130  -0.00  -0.000  Alive',
 '    590  Q13901#1  Quadrupole          319.072   0.053   19.19   4.400   0.00  -0.000   50.84   4.191  -0.00  -0.000  Alive',
 '    592  Q13901#2  Quadrupole          319.126   0.053   19.24   4.400   0.00  -0.000   50.72   4.191  -0.00  -0.000  Alive',
 '    601  Q14201#1  Quadrupole          333.942   0.053   58.71   4.473   0.00  -0.000   11.98   4.294   0.00  -0.000  Alive',
 '    603  Q14201#2  Quadrupole          333.996   0.053   58.49   4.473   0.00  -0.000   12.01   4.295   0.00  -0.000  Alive',
 '    614  Q14301#1  Quadrupole          346.287   0.053    7.80   4.571   0.00  -0.000   42.22   4.387   0.00  -0.000  Alive',
 '    616  Q14301#2  Quadrupole          346.340   0.053    7.78   4.572   0.00  -0.000   42.12   4.387   0.00  -0.000  Alive',
 '    627  Q14401#1  Quadrupole          358.631   0.053   25.26   4.742  -0.00   0.000   12.30   4.478   0.00  -0.000  Alive',
 '    629  Q14401#2  Quadrupole          358.685   0.053   25.22   4.742  -0.00   0.000   12.33   4.478   0.00  -0.000  Alive',
 '    640  Q14501#1  Quadrupole          370.976   0.053   13.11   4.860  -0.00   0.000   45.72   4.565   0.00   0.000  Alive',
 '    642  Q14501#2  Quadrupole          371.029   0.053   13.16   4.861  -0.00   0.000   45.77   4.565   0.00   0.000  Alive',
 '    653  Q14601#1  Quadrupole          383.320   0.053   42.68   4.947  -0.00   0.000   48.69   4.607   0.00   0.000  Alive',
 '    655  Q14601#2  Quadrupole          383.373   0.053   42.71   4.948  -0.00   0.000   48.90   4.607   0.00   0.000  Alive',
 '    674  Q14701#1  Quadrupole          395.664   0.053   40.57   4.996  -0.00   0.000  137.04   4.631   0.00   0.000  Alive',
 '    676  Q14701#2  Quadrupole          395.718   0.053   41.16   4.996  -0.00   0.000  135.58   4.631   0.00   0.000  Alive',
 '    680  QM14715#1 Quadrupole          397.705   0.053   75.22   5.001  -0.00   0.000   69.05   4.635   0.00   0.000  Alive',
 '    682  QM14715#2 Quadrupole          397.758   0.053   75.27   5.002  -0.00   0.000   68.48   4.635   0.00   0.000  Alive',
 '    688  CQ14738   Quadrupole          400.920   0.176   58.60   5.009  -0.10   0.000   54.29   4.643   0.00   0.000  Alive',
 '    702  CQ14866   Quadrupole          418.889   0.176    8.87   5.153  -0.09   0.000    9.56   4.782  -0.00   0.000  Alive',
 '    713  QM14891#1 Quadrupole          422.255   0.053    8.24   5.218   0.00  -0.000    8.76   4.842  -0.00   0.000  Alive',
 '    715  QM14891#2 Quadrupole          422.308   0.053    8.14   5.219   0.00  -0.000    8.88   4.843  -0.00   0.000  Alive',
 '    719  Q14901#1  Quadrupole          422.665   0.053    7.33   5.226   0.00  -0.000    9.97   4.849  -0.00   0.000  Alive',
 '    721  Q14901#2  Quadrupole          422.718   0.053    7.33   5.227   0.00  -0.000    9.99   4.850  -0.00   0.000  Alive',
 '    739  Q15201#1  Quadrupole          435.560   0.053   43.54   5.355   0.00  -0.000   18.84   5.044  -0.00  -0.000  Alive',
 '    741  Q15201#2  Quadrupole          435.614   0.053   43.48   5.355   0.00  -0.000   19.10   5.044  -0.00  -0.000  Alive',
 '    754  Q15301#1  Quadrupole          447.905   0.053   17.33   5.429   0.00  -0.000  159.88   5.080  -0.00  -0.000  Alive',
 '    756  Q15301#2  Quadrupole          447.958   0.053   17.39   5.429   0.00  -0.000  159.66   5.080  -0.00  -0.000  Alive',
 '    767  Q15401#1  Quadrupole          460.249   0.053   57.54   5.493   0.00  -0.000   52.95   5.101  -0.00  -0.000  Alive',
 '    769  Q15401#2  Quadrupole          460.303   0.053   57.48   5.493   0.00  -0.000   52.90   5.101  -0.00  -0.000  Alive',
 '    780  Q15501#1  Quadrupole          472.594   0.053   27.74   5.543   0.00  -0.000   68.21   5.134  -0.00  -0.000  Alive',
 '    782  Q15501#2  Quadrupole          472.647   0.053   27.76   5.543   0.00  -0.000   68.04   5.134  -0.00  -0.000  Alive',
 '    793  Q15601#1  Quadrupole          484.938   0.053   46.20   5.599   0.00   0.000   23.29   5.184  -0.00  -0.000  Alive',
 '    795  Q15601#2  Quadrupole          484.991   0.053   46.09   5.599   0.00   0.000   23.27   5.185  -0.00  -0.000  Alive',
 '    806  Q15701#1  Quadrupole          497.282   0.053   17.45   5.670  -0.00   0.000   34.25   5.256  -0.00  -0.000  Alive',
 '    808  Q15701#2  Quadrupole          497.336   0.053   17.47   5.671  -0.00   0.000   34.15   5.256  -0.00  -0.000  Alive',
 '    819  Q15801#1  Quadrupole          509.627   0.053   40.64   5.747  -0.00   0.000   11.05   5.366   0.00  -0.000  Alive',
 '    821  Q15801#2  Quadrupole          509.680   0.053   40.52   5.747  -0.00   0.000   11.09   5.366   0.00  -0.000  Alive',
 '    836  Q15901#1  Quadrupole          522.290   0.053    9.30   5.860  -0.00   0.000   46.29   5.460   0.00  -0.000  Alive',
 '    838  Q15901#2  Quadrupole          522.344   0.053    9.32   5.861  -0.00   0.000   46.21   5.460   0.00  -0.000  Alive',
 '    849  Q16201#1  Quadrupole          537.160   0.053   46.92   5.986  -0.00   0.000   13.35   5.562   0.00   0.000  Alive',
 '    851  Q16201#2  Quadrupole          537.214   0.053   46.82   5.986  -0.00   0.000   13.40   5.563   0.00   0.000  Alive',
 '    862  Q16301#1  Quadrupole          549.505   0.053   14.56   6.064  -0.00   0.000   48.61   5.643   0.00   0.000  Alive',
 '    864  Q16301#2  Quadrupole          549.558   0.053   14.59   6.065  -0.00   0.000   48.48   5.643   0.00   0.000  Alive',
 '    875  Q16401#1  Quadrupole          561.849   0.053   44.68   6.145   0.00  -0.000   11.88   5.729   0.00   0.000  Alive',
 '    877  Q16401#2  Quadrupole          561.903   0.053   44.57   6.145   0.00  -0.000   11.88   5.729   0.00   0.000  Alive',
 '    888  Q16501#1  Quadrupole          574.194   0.053   13.04   6.230   0.00  -0.000   32.86   5.836  -0.00   0.000  Alive',
 '    890  Q16501#2  Quadrupole          574.247   0.053   13.06   6.231   0.00  -0.000   32.80   5.836  -0.00   0.000  Alive',
 '    901  Q16601#1  Quadrupole          586.538   0.053   37.95   6.324   0.00  -0.000   13.49   5.936  -0.00   0.000  Alive',
 '    903  Q16601#2  Quadrupole          586.591   0.053   37.87   6.324   0.00  -0.000   13.55   5.936  -0.00   0.000  Alive',
 '    914  Q16701#1  Quadrupole          598.882   0.053   13.53   6.415   0.00  -0.000   52.40   6.013  -0.00  -0.000  Alive',
 '    916  Q16701#2  Quadrupole          598.936   0.053   13.57   6.416   0.00  -0.000   52.29   6.013  -0.00  -0.000  Alive',
 '    927  Q16801#1  Quadrupole          611.227   0.053   47.59   6.496   0.00  -0.000   16.30   6.082  -0.00  -0.000  Alive',
 '    929  Q16801#2  Quadrupole          611.280   0.053   47.46   6.496   0.00  -0.000   16.33   6.082  -0.00  -0.000  Alive',
 '    944  Q16901#1  Quadrupole          623.890   0.053   11.06   6.589   0.00   0.000   46.65   6.158  -0.00  -0.000  Alive',
 '    946  Q16901#2  Quadrupole          623.944   0.053   11.07   6.590   0.00   0.000   46.52   6.158  -0.00  -0.000  Alive',
 '    955  Q17201#1  Quadrupole          638.760   0.053   42.76   6.709  -0.00   0.000    7.99   6.298   0.00  -0.000  Alive',
 '    957  Q17201#2  Quadrupole          638.814   0.053   42.65   6.709  -0.00   0.000    8.01   6.299   0.00  -0.000  Alive',
 '    968  Q17301#1  Quadrupole          651.105   0.053   11.81   6.802  -0.00   0.000   40.34   6.419   0.00  -0.000  Alive',
 '    970  Q17301#2  Quadrupole          651.158   0.053   11.83   6.802  -0.00   0.000   40.29   6.419   0.00  -0.000  Alive',
 '    981  Q17401#1  Quadrupole          663.449   0.053   40.28   6.897  -0.00   0.000   16.55   6.498   0.00   0.000  Alive',
 '    983  Q17401#2  Quadrupole          663.503   0.053   40.21   6.898  -0.00   0.000   16.60   6.498   0.00   0.000  Alive',
 '    994  Q17501#1  Quadrupole          675.794   0.053   14.70   6.982  -0.00   0.000   54.77   6.565   0.00   0.000  Alive',
 '    996  Q17501#2  Quadrupole          675.847   0.053   14.74   6.983  -0.00   0.000   54.65   6.565   0.00   0.000  Alive',
 '   1007  Q17601#1  Quadrupole          688.138   0.053   47.15   7.060  -0.00   0.000   15.86   6.634   0.00   0.000  Alive',
 '   1009  Q17601#2  Quadrupole          688.191   0.053   47.04   7.060  -0.00   0.000   15.87   6.634   0.00   0.000  Alive',
 '   1020  Q17701#1  Quadrupole          700.482   0.053   14.80   7.137   0.00  -0.000   37.35   6.718   0.00   0.000  Alive',
 '   1022  Q17701#2  Quadrupole          700.536   0.053   14.83   7.138   0.00  -0.000   37.23   6.719   0.00   0.000  Alive',
 '   1033  Q17801#1  Quadrupole          712.827   0.053   42.12   7.220   0.00  -0.000    9.83   6.830  -0.00   0.000  Alive',
 '   1035  Q17801#2  Quadrupole          712.880   0.053   41.99   7.220   0.00  -0.000    9.86   6.831  -0.00   0.000  Alive',
 '   1050  Q17901#1  Quadrupole          725.490   0.053    8.96   7.333   0.00  -0.000   42.82   6.936  -0.00   0.000  Alive',
 '   1052  Q17901#2  Quadrupole          725.544   0.053    8.97   7.333   0.00  -0.000   42.75   6.936  -0.00   0.000  Alive',
 '   1061  Q18201#1  Quadrupole          740.360   0.053   45.83   7.464   0.00  -0.000   13.32   7.043  -0.00  -0.000  Alive',
 '   1063  Q18201#2  Quadrupole          740.414   0.053   45.74   7.464   0.00  -0.000   13.37   7.043  -0.00  -0.000  Alive',

In [9]:
tao.cmd("show ele CQ14738")

['Element # 688',
 'Element Name: CQ14738',
 'Element Type:  "2.1Q5.87"',
 'Element Alias:  "QUAD:LI14:738"',
 'Key: Quadrupole',
 'S_start, S:    400.743998,    400.919898',
 'Ref_time_start, Ref_time:  1.336755E-06,  1.337342E-06',
 '',
 'Attribute values [Only non-zero values shown]:',
 '    1  L                           =  1.7590000E-01 m',
 '    4  K1                          = -2.2876847E-03 1/m^2    45  B1_GRADIENT                 =  3.4327088E-02 T/m',
 '   10  FRINGE_TYPE                 =  None (1)               11  FRINGE_AT                   =  Both_Ends (3)',
 '   13  SPIN_FRINGE_ON              =  T (1)',
 '   17  STATIC_LINEAR_MAP           =  F (0)',
 '   47  PTC_CANONICAL_COORDS        =  T (1)',
 '   53  P0C                         =  4.4984355E+09 eV           BETA                        =  9.9999999E-01',
 '   54  E_TOT                       =  4.4984356E+09 eV           GAMMA                       =  8.8032188E+03',
 '   64  REF_TIME_START              =  1.3367551E-06 sec      50  DELTA_REF_TIME              =  5.8673925E-10 sec',
 '   65  INTEGRATOR_ORDER            = 2',
 '   67  DS_STEP                     =  1.7590000E-01 m        66  NUM_STEPS                   = 1',
 '   68  CSR_DS_STEP                 =  0.0000000E+00 m',
 '   71  X1_LIMIT                    =  2.6670000E-02 m        72  X2_LIMIT                    =  2.6670000E-02 m',
 '   73  Y1_LIMIT                    =  2.6670000E-02 m        74  Y2_LIMIT                    =  2.6670000E-02 m',
 '',
 '       TRACKING_METHOD              =  Bmad_Standard             APERTURE_AT                =  Exit_End',
 '       MAT6_CALC_METHOD             =  Auto                      APERTURE_TYPE              =  Rectangular',
 '       SPIN_TRACKING_METHOD         =  Tracking                  OFFSET_MOVES_APERTURE      =  F',
 '       PTC_INTEGRATION_TYPE         =  Matrix_Kick               SYMPLECTIFY                =  F',
 '       CSR_METHOD                   =  1_Dim                     FIELD_MASTER               =  F',
 '       SPACE_CHARGE_METHOD          =  Off                       LONGITUDINAL ORIENTATION   =       1',
 '       FIELD_CALC                   =  Bmad_Standard             REF_SPECIES                =  Electron',
 '',
 'Slave_status: Free',
 '',
 'Lord_status:  Not_a_Lord',
 '',
 'Twiss at end of element:',
 '                          A              B            Cbar                        C_mat',
 '  Beta (m)        58.59779168    54.29426659  |  -0.00000000  -0.00000000     -0.00000000  -0.00000000',
 '  Alpha            2.48000671     2.10276226  |   0.00000000  -0.00000000      0.00000000   0.00000000',
 '  Gamma (1/m)      0.12202564     0.09985602  |   Gamma_c =   1.00000000       Mode_Flip = F',
 '  Phi (rad)       31.47289703    29.17224796            X              Y              Z',
 '  Eta (m)         -0.09962320    -0.00000000    -0.09962320     0.00000000    -0.02221130',
 '  Etap            -0.04194457     0.00000000    -0.04194457    -0.00000000    -0.00000000',
 '  dEta/ds         -0.04194457     0.00000000    -0.04194457    -0.00000000    -0.00000000',
 '',
 'Tracking: Electron,   State: Alive',
 '         Position[mm] Momentum[mrad]        Spin   |',
 '  X:       0.00000000     0.00000000               | t_particle [sec]:        1.33734186E-06  E_tot: 4.49844E+09',
 '  Y:       0.00000000    -0.00000000               | t_part-t_ref [sec]:      0.00000000E+00  PC:    4.49844E+09',
 '  Z:       0.00000000    -0.00000000               | (t_ref-t_part)*Vel [m]:  0.00000000E+00  Beta:  0.999999994']

In [10]:
tao.cmd("change ele CQ14738 B1_GRADIENT 0.01")
newMatrix = getMatrix(tao, "BEGBC14_1", "ENDBC14_2", print = True)
displayMatrix(newMatrix - baselineTransport)